create table orders (
    id bigint generated by default as identity primary key,
    customer_id uuid not null,
    total_cents bigint not null,
    created_at timestamp(6) with time zone not null
);

create table order_item (
    id bigint generated by default as identity primary key,
    order_id bigint not null references orders (id),
    seat_id bigint not null unique references seat (id),
    price_cents bigint not null
);

create index idx_order_item_order on order_item (order_id);
